import FloatElements from '@/components/FloatElements';
import Footer from '@/components/footer/components';
import NavMobile from '@/components/nav-mobile/components';
import TranslationsProvider from '@/components/TranslationProvider';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { Toaster } from '@/components/ui/toaster';
import { StateProvider } from '@/store';
import { dir } from 'i18next';
import localFont from 'next/font/local';
import Head from 'next/head';
import { Suspense } from 'react';
import i18nConfig from '../../../i18nConfig';
import Header from '../../components/Header/components';
import SidebarSection from '../../components/SidebarSection';
import initTranslations from '../i18n';
import ChatModule from './@chat/page';
import LoginSignup from './@login/page';
import './global.scss';

import SocketProvider from './SocketProvider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Fishbet stars',
  description: 'Generated by Fishbet stars',
};
const i18nNamespaces = ['home'];

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params: { locale } }) {
  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html
      lang={locale}
      dir={dir(locale)}
      className={`${geistSans.variable} ${geistMono.variable} `}
    >
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="antialiased h-full" suppressHydrationWarning>
        {/* pixi integration for wheel spin */}
        <script src="/assets/pixi-assets/js/pixi-legacy.min.js" defer />
        {/* <CustomOrionStarLoading /> */}
        <main>
          <Suspense fallback={<div>Loading...</div>}>
            <StateProvider>
              <TranslationsProvider
                namespaces={i18nNamespaces}
                locale={locale}
                resources={resources}
              >
                <LoginSignup />
                <SocketProvider>
                  <SidebarProvider>
                    <SidebarSection />
                    <SidebarInset>
                      <Header />
                      <div className="h-[calc(100vh-121px)] md:h-[calc(100vh-63px)] w-full overflow-y-auto scrollbar-thin scrollable-Content-Home">
                        <div className="w-full px-[4vw] py-4 bg-[hsl(var(--main-background))] ">
                          <div className="max-w-[1200px] mx-auto">
                            {children}
                          </div>
                        </div>
                        <FloatElements />
                        <Footer />
                      </div>

                      <NavMobile />
                    </SidebarInset>
                    <ChatModule />
                  </SidebarProvider>
                </SocketProvider>
              </TranslationsProvider>
              <Toaster />
            </StateProvider>
          </Suspense>
        </main>
      </body>
    </html>
  );
}
